<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>4. textarea_Enquiry</name>
   <tag></tag>
   <elementGuidId>358b284d-3153-46d5-9308-5d9ac3df3ad2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Enquiry</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Enquiry']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter your enquiry&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b5570814-8fec-40c0-9c9f-6ee289129b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enquiry</value>
      <webElementGuid>79a6670b-3b53-4153-97a6-1d360d9c70fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>d7add999-2c96-4fc6-a0b8-1072a2cd0dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a3553c44-acf4-4f28-8c15-8482de4f5049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Enter enquiry</value>
      <webElementGuid>ec996fdc-ff68-4bcb-94ab-e17efc022544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Enquiry</value>
      <webElementGuid>649434b3-c5df-4d5a-af77-8930cdb434ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Enquiry</value>
      <webElementGuid>65b896f9-ba5b-4c65-a491-b1bb4bb83b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your enquiry</value>
      <webElementGuid>3e2f73cd-bab6-4ccb-8cb4-1d6cbc5e1e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>c4eceff1-a340-4737-9db8-b83fb7b4dedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Enquiry&quot;)</value>
      <webElementGuid>f6abd093-ad8b-44bc-8b53-70e1d5a10473</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Enquiry']</value>
      <webElementGuid>ff7d1238-fd8a-46bc-b80b-a370d7435cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3d5b017d-c686-4b0e-ab76-486b64a72b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Enquiry' and @name = 'Enquiry' and @placeholder = 'Enter your enquiry']</value>
      <webElementGuid>57c4d3f5-24e6-40d6-9d62-4a3c940bae36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
