<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>2. input_Gender</name>
   <tag></tag>
   <elementGuidId>0d27672d-7106-479d-a085-368f55e9b0ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gender-male</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[2]/div[2]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>330e2f27-1069-420d-9374-84f5e1d61edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gender-male</value>
      <webElementGuid>67f410f7-b54c-4d14-bd68-572222963165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Gender</value>
      <webElementGuid>680f549b-4c37-429c-bd8b-b74941281a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2ebf1454-859b-4275-b910-3a9a664bf8c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>c7c43c95-9830-4fef-8d6e-398aa150640c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gender-male&quot;)</value>
      <webElementGuid>e52246ab-a2b2-449b-b10f-627934c6c6bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gender-male']</value>
      <webElementGuid>7acc6a74-f624-4ea1-bef3-1317e0d1268e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>e87a4f51-a614-4d9e-b460-bc10b4adc4d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gender-male' and @name = 'Gender' and @type = 'radio']</value>
      <webElementGuid>53d536ba-427f-40f8-8808-ef4bea906040</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
