<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>3. input_Male</name>
   <tag></tag>
   <elementGuidId>f695e9de-a674-47e3-9ea7-06004de0027e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gender-female</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gender-female']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0454533-0126-49e6-bbbb-5605bb78c2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gender-female</value>
      <webElementGuid>25dcb2f7-f5ff-4715-bae5-5e1b2d8302be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Gender</value>
      <webElementGuid>4765fd0a-1cf0-406c-88bd-f2706134514b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6864948e-b50f-41ad-89f8-1de74a02b038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>F</value>
      <webElementGuid>320da0d2-b3c0-433f-a0fa-985fb13f2f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gender-female&quot;)</value>
      <webElementGuid>779e87ef-e9ed-445b-b32f-6d68ead47212</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gender-female']</value>
      <webElementGuid>c03b518f-2678-473c-8b69-ffdc43ea0de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div[2]/input</value>
      <webElementGuid>05986a76-0655-44b9-a7df-97982a79004a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gender-female' and @name = 'Gender' and @type = 'radio']</value>
      <webElementGuid>99bb2f4d-cc35-4f42-be42-4dcd92f281f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
