<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>8GB-attribute_72_6_19</name>
   <tag></tag>
   <elementGuidId>4f854e97-a622-4492-a866-5b54153bb6c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product_attribute_72_6_19_91</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product_attribute_72_6_19_91']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;8 GB  [+60.00]&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8efcc5e7-2a44-4f9a-8086-7e186962026a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_attribute_72_6_19_91</value>
      <webElementGuid>34faccf8-90d6-464a-a432-c28e0ae6a45c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6e6cc944-ae38-42d4-85c1-250c55e3bc78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product_attribute_72_6_19</value>
      <webElementGuid>8ee21af8-c418-4f35-bc15-f53f033db34b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>91</value>
      <webElementGuid>77be3c9b-1616-4cfd-8ab1-d5880a727e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_attribute_72_6_19_91&quot;)</value>
      <webElementGuid>9aca9209-38df-4d93-b697-50536ad2b163</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_attribute_72_6_19_91']</value>
      <webElementGuid>72ea2ed7-0dac-426e-9afc-47069b52a1de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div/div/div[2]/div[6]/dl/dd[2]/ul/li/input</value>
      <webElementGuid>9d8b33f1-919e-4f8c-8064-a3f3ccd1d2ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dd[2]/ul/li/input</value>
      <webElementGuid>cf0e251d-0412-47c3-90a9-472c882a4110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'product_attribute_72_6_19_91' and @type = 'radio' and @name = 'product_attribute_72_6_19']</value>
      <webElementGuid>9f1ba34b-6a81-46ee-beb7-cfa83799c7bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
