<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a12. OldPassword</name>
   <tag></tag>
   <elementGuidId>92d0d91b-d012-4bcf-bef3-0dd1eed45042</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OldPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='OldPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Old password:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f09e0afb-0604-4bdf-a5bd-c69aacc406e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line password</value>
      <webElementGuid>a0559998-9f69-4b7b-ae25-448e0ed4d399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>25b87481-a81c-4eb7-9bbd-2a2927ae757e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Old password is required.</value>
      <webElementGuid>4fefbb07-8838-43a7-b83b-1a01949e5858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OldPassword</value>
      <webElementGuid>422a546d-1e73-4dca-a9e0-fae2e0ff837e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OldPassword</value>
      <webElementGuid>812b044c-d4c5-4f55-b711-82f7c54bb733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c921d3d3-1202-477b-aab1-3102331aec6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OldPassword&quot;)</value>
      <webElementGuid>b41a5bea-3ee6-458c-85cc-1b08e66fe3d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OldPassword']</value>
      <webElementGuid>0bab0c98-e64f-4749-ae1e-6733b94830b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>613953d1-1dff-4b63-bdc7-b7466e5b0b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'OldPassword' and @name = 'OldPassword' and @type = 'password']</value>
      <webElementGuid>70e28df2-2092-4730-b3c4-1423133ce050</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
