<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>8. input_termsofservice</name>
   <tag></tag>
   <elementGuidId>c26e6e39-6d36-4b36-b84f-aba979e45687</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#termsofservice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='termsofservice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#termsofservice</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>543023c7-e45d-48e8-b180-76152e635ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>termsofservice</value>
      <webElementGuid>808539c1-feee-42e9-8709-bd9041cfed72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>87062489-708e-4fb9-b77d-6b9893f6a5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>termsofservice</value>
      <webElementGuid>3b65aaaf-e1d5-41e6-a45a-19c2a8f27712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;termsofservice&quot;)</value>
      <webElementGuid>7d1297b1-d3aa-44f8-89ec-9a4e57779846</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='termsofservice']</value>
      <webElementGuid>208e6768-7a7b-4a5c-bbf2-cc986ab974a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/input</value>
      <webElementGuid>486488f0-8ded-4a67-ab00-ee97f80f1b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'termsofservice' and @type = 'checkbox' and @name = 'termsofservice']</value>
      <webElementGuid>0371f4da-d508-43ab-b66c-9f296dcbb3c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
