<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>7. input_Heart_product</name>
   <tag></tag>
   <elementGuidId>b3e9308a-5667-4f65-8598-b3a4b7e83e72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product_attribute_71_11_17_50']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product_attribute_71_11_17_50</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Star&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44b5f842-3735-434c-bc32-ad07280fa549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_attribute_71_11_17_50</value>
      <webElementGuid>6e600109-b6ea-4ab5-bb33-2e6bb7281325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1335aa22-e9d9-4019-ba24-26007a62f695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product_attribute_71_11_17</value>
      <webElementGuid>3df2a6b9-e008-4306-9f60-0e64997ffc82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>25841bcd-55e7-40ef-add6-05988a7a5ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_attribute_71_11_17_50&quot;)</value>
      <webElementGuid>7d49607b-e1dd-4fb2-be04-17a2b6e22ea3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_attribute_71_11_17_50']</value>
      <webElementGuid>8d3aee3b-b6df-45a4-b64b-bbbdc297e160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div/div/div[2]/div[4]/dl/dd[3]/ul/li[3]/input</value>
      <webElementGuid>0590ba3d-9321-48b0-94f1-cb2c7401ca2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/input</value>
      <webElementGuid>34bb0ce9-90db-4d1a-81d9-39593662118a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'product_attribute_71_11_17_50' and @type = 'radio' and @name = 'product_attribute_71_11_17']</value>
      <webElementGuid>a4fb2725-eaeb-4c23-b71e-6f663da2de95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
