<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>5. EnteredQuantity</name>
   <tag></tag>
   <elementGuidId>9a1b05ce-2c83-431d-8371-3ae0b9b60991</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addtocart_31_EnteredQuantity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addtocart_31_EnteredQuantity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Qty:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0fcac043-b272-4d02-890f-e352c9e6f772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qty-input</value>
      <webElementGuid>90c55bc0-31ca-4a84-8293-10bf5044f4a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>28f80839-9848-401c-bc9f-a8dc3bdc71a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Qty must be a number.</value>
      <webElementGuid>34a75d67-a8fe-4001-8895-840696792047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addtocart_31_EnteredQuantity</value>
      <webElementGuid>293c9b67-7a71-49fe-845b-8a55682dd7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addtocart_31.EnteredQuantity</value>
      <webElementGuid>e1c1f2a4-0654-472a-b152-7b5cafb88319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a77301be-8c06-4160-a7fc-2a72c8912e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a4ce1b38-24a4-40a5-a648-49fec2d82fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addtocart_31_EnteredQuantity&quot;)</value>
      <webElementGuid>87f96b88-efc3-4c87-b8ed-990581a60bca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addtocart_31_EnteredQuantity']</value>
      <webElementGuid>333956fa-3d37-449c-9697-33ca65e17461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div/div/div[2]/div[6]/div/input</value>
      <webElementGuid>cb04a649-2030-40ed-afa9-df2909db5cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>08904e3a-3af2-4bec-a0dc-b6775ecc0fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addtocart_31_EnteredQuantity' and @name = 'addtocart_31.EnteredQuantity' and @type = 'text']</value>
      <webElementGuid>6e2bba33-2245-4059-93f6-b80cd2b67028</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
