<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a16. select_VisaMaster</name>
   <tag></tag>
   <elementGuidId>f9f5a6e3-b707-4ead-921c-6e2a4f268186</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CreditCardType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='CreditCardType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#CreditCardType</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>27ed3d7e-f61e-416c-81a3-9e5533041612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdownlists</value>
      <webElementGuid>32b076aa-dbd8-43d7-ae52-b47e39ff9578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CreditCardType</value>
      <webElementGuid>8b90ae4f-0a33-48b7-8efb-85fdd3cec8b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CreditCardType</value>
      <webElementGuid>c7eea015-d0c3-4b5c-aa04-669cd4bdb12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Visa
Master card
Discover
Amex
</value>
      <webElementGuid>33fdde8f-09d5-4575-85ce-5c37c59f3783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CreditCardType&quot;)</value>
      <webElementGuid>180dc589-4d70-4780-bf26-1841ba24f90e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='CreditCardType']</value>
      <webElementGuid>ff7d6f5d-8566-42ac-893b-bf01f882079f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-payment-info-load']/div/div/div/table/tbody/tr/td[2]/select</value>
      <webElementGuid>ca20536f-d949-40cc-aade-a01fd73d8188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select credit card'])[1]/following::select[1]</value>
      <webElementGuid>321712af-c102-444f-8914-985454887251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cardholder name'])[1]/preceding::select[1]</value>
      <webElementGuid>ff716caa-211a-4664-bfba-0093daec288a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/select</value>
      <webElementGuid>beda6783-3443-4569-ba2c-e77b79174014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'CreditCardType' and @name = 'CreditCardType' and (text() = 'Visa
Master card
Discover
Amex
' or . = 'Visa
Master card
Discover
Amex
')]</value>
      <webElementGuid>fc7819a6-d386-4bb4-8d95-a0abea6da348</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
