<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a17. CardholderName</name>
   <tag></tag>
   <elementGuidId>3e9cd27c-43b6-4508-9984-ee355c873ed0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CardholderName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CardholderName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Cardholder name&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>478074c9-cb14-4e95-8078-5e9bc45f2893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d4934328-a198-41b1-a342-688397ef6f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CardholderName</value>
      <webElementGuid>2d6ff581-78e3-4afb-9e92-5c55742aabc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CardholderName</value>
      <webElementGuid>92541bd9-1734-4778-bd8b-17107b278fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8c2b7429-204b-48e9-a6a2-a707c1ed43ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardholderName&quot;)</value>
      <webElementGuid>b7d26d54-e6d1-43d7-b24c-76f6dbfa418b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CardholderName']</value>
      <webElementGuid>9bcdc107-8520-4fe9-ae4a-9b17170552d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-payment-info-load']/div/div/div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>4a69d998-4ad9-4092-924a-364821342ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>ad114292-72ae-4c31-9272-ee8ed8286c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CardholderName' and @name = 'CardholderName' and @type = 'text']</value>
      <webElementGuid>26e1619b-7922-4f3b-970c-147a1677bc20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
