<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a24. confirm-order-next-step-button</name>
   <tag></tag>
   <elementGuidId>91812c3b-2bf1-4262-b098-575574bd2d4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.button-1.confirm-order-next-step-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Confirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Confirm&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>785bf528-0440-4d68-8e2f-c4ce0d0ac9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2fd3c079-4256-465b-a93f-959cc68763c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-1 confirm-order-next-step-button</value>
      <webElementGuid>2c99fa51-87e4-4a56-ada3-bfd03910b6a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ConfirmOrder.save()</value>
      <webElementGuid>8f55fc95-aff5-4be5-94c7-7ed3ec131faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Confirm</value>
      <webElementGuid>0408dcc4-8eec-410f-bc94-9e0e97fcdbf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirm-order-buttons-container&quot;)/input[@class=&quot;button-1 confirm-order-next-step-button&quot;]</value>
      <webElementGuid>356be92f-922f-4f98-a8db-6f0d47cd1326</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Confirm']</value>
      <webElementGuid>26aa6c41-b3b6-465e-b63d-8eff5269a4d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='confirm-order-buttons-container']/input</value>
      <webElementGuid>ed41a94a-ba42-476b-a1a7-643a426bcbb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>ef85168f-66f5-4339-8110-c025acd8b5ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>35a47118-2028-4233-8083-a8f2af12d600</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
