<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>2.shirt-img</name>
   <tag></tag>
   <elementGuidId>d409ba91-c579-4d1f-9f05-0787ff2ae012</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>2.</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Picture of Men's Wrinkle Free Long Sleeve&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Picture of Men's Wrinkle Free Long Sleeve&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8eb309bd-2c35-476b-bb86-e2d1903e6af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Picture of Men's Wrinkle Free Long Sleeve</value>
      <webElementGuid>a5a39090-2d64-4716-aad3-ad8898c23ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://demowebshop.tricentis.com/content/images/thumbs/0000025_mens-wrinkle-free-long-sleeve_125.jpg</value>
      <webElementGuid>89132eb8-157f-436a-9d67-73d3f3026b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Show details for Men's Wrinkle Free Long Sleeve</value>
      <webElementGuid>6d4c8186-d1df-455e-82cb-f023704cc736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;master-wrapper-page&quot;]/div[@class=&quot;master-wrapper-content&quot;]/div[@class=&quot;master-wrapper-main&quot;]/div[@class=&quot;center-2&quot;]/div[@class=&quot;page category-page&quot;]/div[@class=&quot;page-body&quot;]/div[@class=&quot;product-grid&quot;]/div[@class=&quot;item-box&quot;]/div[@class=&quot;product-item&quot;]/div[@class=&quot;picture&quot;]/a[1]/img[1]</value>
      <webElementGuid>692e9e75-6bbd-49f1-9584-f4fa0a9724c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt=&quot;Picture of Men's Wrinkle Free Long Sleeve&quot;]</value>
      <webElementGuid>aec422f9-b209-4dc3-a2e1-2866c8d94692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/a/img</value>
      <webElementGuid>a27c8bc6-173a-42c1-8962-6239bb3ce0b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = concat(&quot;Picture of Men&quot; , &quot;'&quot; , &quot;s Wrinkle Free Long Sleeve&quot;) and @src = 'https://demowebshop.tricentis.com/content/images/thumbs/0000025_mens-wrinkle-free-long-sleeve_125.jpg' and @title = concat(&quot;Show details for Men&quot; , &quot;'&quot; , &quot;s Wrinkle Free Long Sleeve&quot;)]</value>
      <webElementGuid>3020cb48-ce61-45d2-9ebd-f38cd99fa94b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
