<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fast-attribute_72_5_18</name>
   <tag></tag>
   <elementGuidId>53b1b700-64e0-441f-b563-91e73866a8b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product_attribute_72_5_18_65</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product_attribute_72_5_18_65']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Fast  [+100.00]&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73fea5e5-db46-499c-8acc-2b713c934421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_attribute_72_5_18_65</value>
      <webElementGuid>9149f679-10ae-4bf1-9c60-0525ee3bf288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>7ddab3f4-a9f9-428b-be83-cf120b8f9bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product_attribute_72_5_18</value>
      <webElementGuid>c9f6cf0f-40bf-4c9e-81dc-37fba1cc66bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>65</value>
      <webElementGuid>a3ef52ec-31c2-4408-9e74-01094465ee03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_attribute_72_5_18_65&quot;)</value>
      <webElementGuid>d2418552-1664-44d9-8d61-40ce35f39845</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_attribute_72_5_18_65']</value>
      <webElementGuid>69622d5b-21c4-4357-8445-25ba30aa62a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div/div/div[2]/div[6]/dl/dd/ul/li[3]/input</value>
      <webElementGuid>3c5307b5-a587-4792-8048-3b531f8a2e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/input</value>
      <webElementGuid>7073fbed-9ba4-4f1a-b403-89f0ce76720f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'product_attribute_72_5_18_65' and @type = 'radio' and @name = 'product_attribute_72_5_18']</value>
      <webElementGuid>39eead22-cb31-436e-87ba-ea39140b5b29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
