<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>slow-attribute_72_5_18</name>
   <tag></tag>
   <elementGuidId>8f775233-880b-493f-ac94-d98ed51cd573</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product_attribute_72_5_18_52</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product_attribute_72_5_18_52']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Slow&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa2e43ad-eebe-478a-9df2-b888e32aa4e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_attribute_72_5_18_52</value>
      <webElementGuid>d0e0fde1-010f-465d-b7d6-d67e3e8ab19f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a97920b0-fd35-4aa6-adc0-3a59ea4cb313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product_attribute_72_5_18</value>
      <webElementGuid>c1820d6d-d44c-4e3b-a07b-5893e52e2107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>52</value>
      <webElementGuid>915a01f5-1b92-46a9-918c-721bd83197a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_attribute_72_5_18_52&quot;)</value>
      <webElementGuid>00d72bae-47ac-4b5c-aa5c-fcda0baf5ee5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_attribute_72_5_18_52']</value>
      <webElementGuid>f67a11a9-ac98-4f17-95c5-38338be092ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div/div/div[2]/div[6]/dl/dd/ul/li/input</value>
      <webElementGuid>298df926-2628-43b2-be6b-ddb6e1267a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>bcbdc7f1-c2d3-4438-b948-ea407e5fd80f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'product_attribute_72_5_18_52' and @type = 'radio' and @name = 'product_attribute_72_5_18']</value>
      <webElementGuid>fd3c75b1-1c2c-4d8d-800c-b4b4b67d260a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
