<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>320GB-attribute_72_3_20</name>
   <tag></tag>
   <elementGuidId>54bd9bd5-72b3-4591-a6fb-a2762971b05f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product_attribute_72_3_20_57</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product_attribute_72_3_20_57']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;320 GB&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0af37759-de12-4fa1-bf1d-e8e785dabcd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_attribute_72_3_20_57</value>
      <webElementGuid>8f3bbaf6-7c67-4eaf-b58b-5829929e7ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>77c2a22f-7337-4454-8ab2-22e41293e661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product_attribute_72_3_20</value>
      <webElementGuid>ac272263-c96d-4b7e-ad42-52a8c760f3f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>57</value>
      <webElementGuid>681ee257-b5cd-43a4-abac-468646ab964a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>81030d20-db78-41b2-b615-35191ab7c7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_attribute_72_3_20_57&quot;)</value>
      <webElementGuid>60eb6df1-ce21-4786-908c-a2e5a271a812</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_attribute_72_3_20_57']</value>
      <webElementGuid>dce86259-ab25-4e5c-bca4-d9cf9a73f4be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div/div/div[2]/div[6]/dl/dd[3]/ul/li/input</value>
      <webElementGuid>853231a0-fae7-4087-92c4-ac04624abe0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dd[3]/ul/li/input</value>
      <webElementGuid>ea019237-804c-4fe0-ba5e-cf73c9639dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'product_attribute_72_3_20_57' and @type = 'radio' and @name = 'product_attribute_72_3_20' and @checked = 'checked']</value>
      <webElementGuid>c32cd8cb-2ad8-40d3-952b-919684ba5f10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
