<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>2. input_Sign up_button</name>
   <tag></tag>
   <elementGuidId>82839073-58d6-4408-bf0e-2e6d3f0ee776</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#newsletter-subscribe-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='newsletter-subscribe-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Subscribe&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54b52fc4-4a41-46d9-8184-b2342c90835a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8936a28b-8b0c-46fa-93ad-fa74e02fe741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Subscribe</value>
      <webElementGuid>fcd3b0ff-2ac2-4667-9a4a-3ec6a372d74b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newsletter-subscribe-button</value>
      <webElementGuid>6fde4c5d-33ff-4b61-97af-d5161de3374d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-1 newsletter-subscribe-button</value>
      <webElementGuid>0e5788e4-b54b-4fbb-ae81-dc8d6dc2ad23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newsletter-subscribe-button&quot;)</value>
      <webElementGuid>8001f097-c541-4916-88a2-c4b9bb29e25f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='newsletter-subscribe-button']</value>
      <webElementGuid>05326897-2e82-4571-baa4-6f08463a7aaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='newsletter-subscribe-block']/div[2]/input</value>
      <webElementGuid>ac729484-154c-45b2-9627-7be0b05b92db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>21c7fff2-35ae-4c38-a608-4f1b42c72a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'newsletter-subscribe-button']</value>
      <webElementGuid>dfa095d1-661f-4235-8015-8e214dff3529</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
